apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - tekton-pipeline-release.yaml
  - tekton-triggers-release.yaml
  - tekton-dashboard-release.yaml
  - tekton-dashboard-ing.yaml
