apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - argocd-ns.yaml
  - argocd.yaml
  - argocd-ing.yaml
  - argocd-metrics-sm.yaml
  - argocd-repo-server-metrics-sm.yaml
  - argocd-server-metrics-sm.yaml
