apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: argo-cd-ui
  namespace: argocd
spec:
  rules:
    - host: argocd-prod.fake
      http:
        paths:
          - path: /
            backend:
              serviceName: argocd-server
              servicePort: http
