apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux-helm-operator
  namespace: flux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flux-helm-operator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: flux-helm-operator
    spec:
      serviceAccountName: flux-helm-operator
      containers:
        - name: flux-helm-operator
          image: docker.io/fluxcd/helm-operator:1.2.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3030
          livenessProbe:
            httpGet:
              port: 3030
              path: /healthz
            initialDelaySeconds: 1
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              port: 3030
              path: /healthz
            initialDelaySeconds: 1
            timeoutSeconds: 5
          args:
            - --enabled-helm-versions=v3
            - --log-format=json
            - --git-timeout=1m
            - --git-poll-interval=5m
            - --charts-sync-interval=3m
            - --update-chart-deps=true
            - --log-release-diffs=false
            - --workers=5
