apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: argocd-ui
spec:
  rules:
    - host: argocd-dev.fake
      http:
        paths:
          - path: /
            backend:
              serviceName: argocd-server
              servicePort: http
